# The name of your Flutter project
name: flutter_task_nxt

# A brief description of your Flutter project
description: "A new Flutter project."

# Version of your project
version: 1.0.0+1

# Specifies the Dart SDK version compatibility for your project
environment:
  sdk: '>=3.2.4 <4.0.0'

# Dependencies required by your project
dependencies:
  # Flutter SDK dependency
  flutter:
    sdk: flutter

  # External dependencies for your project
  cupertino_icons: ^1.0.2
  # responsive UI 
  flutter_screenutil: ^5.9.0
 
  # persistent store for simple data types
  shared_preferences: ^2.2.2
  # loading indicator
  flutter_easyloading: ^3.0.5
  # HTTP client 
  dio: ^5.3.3
  # interceptor for logging HTTP
  pretty_dio_logger: ^1.3.1 
  # display ratings
  flutter_rating_bar: ^4.0.1
  # automatically size text 
  auto_size_text: ^3.0.0
  # load and cache network images
  cached_network_image: ^3.3.0
  # custom bottom sheets
  modal_bottom_sheet: ^3.0.0 
  #Localization
  flutter_localizations:
    sdk: flutter
  intl_translation: ^0.19.0
  intl: ^0.18.0
  # State
  provider: ^6.1.2

# Development dependencies (only needed during development)
dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
  flutter_lints: ^3.0.1

# Flutter-specific configurations
flutter:
  # Indicates that your app follows Material Design guidelines
  uses-material-design: true

  # Asset declarations for your application
  assets:   
    - assets/icons/
    - assets/images/
    - assets/fonts/

  # Font configurations for your application
  fonts:
    - family: SFDisplay
      fonts:
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYBLACKITALIC.OTF
          weight: 900
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYBOLD.OTF
          weight: 800
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYHEAVYITALIC.OTF
          weight: 700
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYLIGHTITALIC.OTF
          weight: 600
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYMEDIUM.OTF
          weight: 500
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYREGULAR.OTF
          weight: 400
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYSEMIBOLDITALIC.OTF
          weight: 300
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYTHINITALIC.OTF
          weight: 200
        - asset: assets/fonts/SFDisplay/SFPRODISPLAYULTRALIGHTITALIC.OTF
          weight: 100
